apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-service-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: task-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-rolebinding
subjects:
- kind: ServiceAccount
  name: task-service-sa
roleRef:
  kind: Role
  name: task-role
  apiGroup: rbac.authorization.k8s.io
